using TMPro; using UnityEngine; using UnityEngine.EventSystems; using UnityEngine.UI;
namespace Overwork.MiniGames.DragDrop {
public sealed class SortingMiniGame:MiniGameBase{
 int remaining,misses; TextMeshProUGUI status; public override void Initialize(int d,float t){base.Initialize(d,t);Build();}
 void Build(){gameObject.AddComponent<Image>().color=new Color(.12f,.16f,.25f,.98f);status=Text("Status",Vector2.zero,Vector2.one,30); var a=Box("INBOX",new Vector2(.08f,.25f),new Vector2(.42f,.72f),"A");var b=Box("ARCHIVE",new Vector2(.58f,.25f),new Vector2(.92f,.72f),"B");Card("MAIL A",new Vector2(.2f,.1f),"A");Card("MAIL B",new Vector2(.5f,.1f),"B");Card("MAIL A",new Vector2(.8f,.1f),"A");remaining=3;Refresh();}
 RectTransform Box(string n,Vector2 min,Vector2 max,string id){var o=new GameObject(n,typeof(RectTransform),typeof(Image),typeof(SortingDropBox));o.transform.SetParent(transform,false);var r=o.GetComponent<RectTransform>();r.anchorMin=min;r.anchorMax=max;r.offsetMin=r.offsetMax=Vector2.zero;o.GetComponent<Image>().color=new Color(.2f,.32f,.45f);o.GetComponent<SortingDropBox>().Configure(this,id);Text(o.transform,n,Vector2.zero,Vector2.one,24);return r;}
 void Card(string n,Vector2 pos,string id){var o=new GameObject(n,typeof(RectTransform),typeof(Image),typeof(CanvasGroup),typeof(SortingDraggable));o.transform.SetParent(transform,false);var r=o.GetComponent<RectTransform>();r.anchorMin=r.anchorMax=pos;r.sizeDelta=new Vector2(150,70);o.GetComponent<Image>().color=new Color(.75f,.58f,.25f);o.GetComponent<SortingDraggable>().Configure(id);Text(o.transform,n,Vector2.zero,Vector2.one,20);}
 TextMeshProUGUI Text(string n,Vector2 min,Vector2 max,float s){var o=new GameObject(n,typeof(RectTransform),typeof(TextMeshProUGUI));o.transform.SetParent(transform,false);var r=o.GetComponent<RectTransform>();r.anchorMin=min;r.anchorMax=max;r.offsetMin=new Vector2(4,4);r.offsetMax=new Vector2(-4,-4);var x=o.GetComponent<TextMeshProUGUI>();x.font=TMP_Settings.defaultFontAsset;x.fontSize=s;x.alignment=TextAlignmentOptions.Center;x.color=Color.white;return x;} void Text(Transform p,string n,Vector2 min,Vector2 max,float s){var t=Text(n,min,max,s);t.transform.SetParent(p,false);}
 public void Drop(SortingDraggable item,bool ok){if(!IsPlaying)return;if(ok){Destroy(item.gameObject);if(--remaining==0)FinishGame(true,"COMPLETE");}else if(++misses>=2)FinishGame(false,"MISSED");Refresh();} protected override void OnUpdate(float d){Refresh();} void Refresh(){if(status!=null)status.text="SORT THE MAIL\nMISS "+misses+" / 2   TIME "+Mathf.CeilToInt(TimeRemaining);}}
public sealed class SortingDraggable:MonoBehaviour,IBeginDragHandler,IDragHandler,IEndDragHandler{string id;RectTransform r;CanvasGroup g;Vector2 start;Transform parent;public void Configure(string v)=>id=v;void Awake(){r=GetComponent<RectTransform>();g=GetComponent<CanvasGroup>();}public void OnBeginDrag(PointerEventData e){start=r.anchoredPosition;parent=transform.parent;g.blocksRaycasts=false;}public void OnDrag(PointerEventData e){r.anchoredPosition+=e.delta;}public void OnEndDrag(PointerEventData e){g.blocksRaycasts=true;if(transform.parent==parent)r.anchoredPosition=start;}public bool Matches(string v)=>id==v;}
public sealed class SortingDropBox:MonoBehaviour,IDropHandler{SortingMiniGame game;string id;public void Configure(SortingMiniGame g,string v){game=g;id=v;}public void OnDrop(PointerEventData e){var item=e.pointerDrag?.GetComponent<SortingDraggable>();if(item!=null)game.Drop(item,item.Matches(id));}}
}
